trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevOps-Images'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'build-windows.sh'
    addSpnToEnvironment: true