trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'windows/*'

jobs:
- job:
  displayName: 'Windows Image'
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-latest

  steps:  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'DevOps-Images'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'windows/build-windows.sh'
      addSpnToEnvironment: true

